name: golangci-lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        env:
          GOPROXY: "https://goproxy.io,direct"
          GO111MODULE: "on"
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.29
          args: --timeout=10m

